# yaml-language-server: $schema=https://raw.githubusercontent.com/golangci/golangci-lint/refs/heads/main/jsonschema/golangci.v2.2.jsonschema.json

version: "2"
run:
  go: "1.24"
  modules-download-mode: readonly
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - iface
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - wsl_v5
    - zerologlint
  disable:
    - gomoddirectives
    - depguard
    - exhaustruct
    - gochecknoglobals
    - godox
    - tagalign
    - tagliatelle
    - testpackage
    - wrapcheck
  settings:
    varnamelen:
      min-name-length: 2
      ignore-decls:
        - w http.ResponseWriter
        - r *http.Request
        - t testing.T
        - e error
        - i int
        - b []byte
        - l *slog.Logger
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    revive:
      rules:
        - name: var-naming
          arguments:
            - [] # AllowList
            - [] # DenyList
            - - skip-package-name-checks: true
    goconst:
      ignore-string-values:
        - 'ID.+'
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
        path: (internal/app/.*|cmd/voyah-free-update-fix/main\.go)$
      - linters:
          - revive
        path: internal/infrastructure/repository/project/project.go
      - linters:
          - funlen
        source: ^func Test
      - linters:
          - funlen
        source: mainInit
      - linters:
          - err113
          - dupl
          - maintidx
        path: _test\.go$
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
